/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  wing: [
    'desktop/wing/Introduce',
    'desktop/wing/Get start',
    'desktop/wing/User guide',
    'desktop/wing/Develop guide',
    'desktop/wing/readme-manager',
    'desktop/wing/readme-developer',
  ],

  tinyui: [
    'desktop/tinyui/Introduce',
    'desktop/tinyui/User guide',
    'desktop/tinyui/Develop guide',
  ],

  cabin: [
    'desktop/cabin/Introduce',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   collapsed: false,
    //   items: [
    //     'desktop/cabin/get-start'
    //   ],
    // },
  ],

  mobtools: [
    'desktop/mobtools/Introduce',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   collapsed: false,
    //   items: [
    //     'desktop/mobtools/get-start'
    //   ],
    // },
  ],

  binderceptor: [
    'mobile/binderceptor/Introduce',
    'mobile/binderceptor/sdk',
  ],

  konker: [
    'mobile/konker/Introduce',
  ],

  packit: [
    'mobile/packit/Introduce',
  ],

  testbot: [
    'services/testbot/Introduce',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   collapsed: false,
    //   items: [
    //     'services/testbot/get-start'
    //   ],
    // },
  ],

  glacier: [
    'services/glacier/Introduce',
  ],

  publishing: [
    'services/publishing/Introduce',
  ],

  udid: [
    'services/udid/Introduce',
  ],

  about: [
    'about/Introduce',
    'about/team',
    'about/privacy',
  ],
};

export default sidebars;
