/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  wing: [
    'desktop/wing/Introduce',
    'desktop/wing/Get start',
    'desktop/wing/User guide',
    'desktop/wing/Develop guide',
  ],

  tinyui: [
    'desktop/tinyui/Introduce',
    'desktop/tinyui/User guide',
    'desktop/tinyui/Develop guide',
  ],

  cabin: [
    'desktop/cabin/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'desktop/cabin/get-start'
      ],
    },
  ],

  mobtools: [
    'desktop/mobtools/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'desktop/mobtools/get-start'
      ],
    },
  ],

  binderceptor: [
    'mobile/binderceptor/Introduce',
  ],

  konker: [
    'mobile/konker/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'mobile/konker/get-start'
      ],
    },
  ],

  packer: [
    'mobile/packer/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'mobile/packer/get-start'
      ],
    },
  ],

  testbot: [
    'services/testbot/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'services/testbot/get-start'
      ],
    },
  ],

  publishing: [
    'services/publishing/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'services/publishing/get-start'
      ],
    },
  ],

  udid: [
    'services/udid/Introduce',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'services/udid/get-start'
      ],
    },
  ],
};

export default sidebars;
